### PR TITLE
Updated AStar Pro importer

### PR DESCRIPTION
**Pull request by zcxv**
Updated AStar Pro importer to 4.1.16 version. That version (or lesser, I dont known) have graph connection changes. 
Also I add BVTree stub for empty tiles: in some cases AStar Pro can export a few tiles with empty nodes (if generation bounds height equals landscape height).

### CODE REVIEW

**Comment by ppiastucki** [comment]
Looks good. Any chance you can add a test related to the new file format similar to https://github.com/ppiastucki/recast4j/blob/master/detour-extras/src/test/java/org/recast4j/detour/extras/unity/astar/UnityAStarPathfindingImporterTest.java?

**Comment by zcxv** [comment]
No problem.

**Comment by zcxv** [comment]
Done.
Also I fix bug with tile width & height calculation: in nav_test map with 0.5 cell size, tile size 128, min region size 3, agent radius 1.5 and bounds ~(91;21;77) tile width/height calculation from bounds was broken. I use AStar voxels tile width/height values (of course translated to world size).

**Comment by ppiastucki** [comment]
Thanks

**Pull request merged**
